'use strict'

export const LOGOUT = Object.freeze('LOGOUT')
export const REGISTER = Object.freeze('REGISTER')
export const LOGIN = Object.freeze('LOGIN')
export const REQUEST_ACCESS_TOKEN = Object.freeze('REQUEST_ACCESS_TOKEN')
export const REQUEST_REFRESH_TOKEN = Object.freeze('REQUEST_REFRESH_TOKEN')
export const GET_BEARER_TOKEN = Object.freeze('GET_BEARER_TOKEN')
export const IS_AUTHENTICATED = Object.freeze('IS_AUTHENTICATED')
export const MUST_REFRESH_TOKEN = Object.freeze('MUST_REFRESH_TOKEN')
export const GET_USER = Object.freeze('GET_USER')
export const GET_PROFILE = Object.freeze('GET_PROFILE')
export const GET_USER_ID = Object.freeze('GET_USER_ID')
export const HAS_ROLE = Object.freeze('HAS_ROLE')
export const HAS_ANY_ROLE = Object.freeze('HAS_ANY_ROLE')
