'use strict'

export const CERTIFICATIONS_NAME_MIN = 1
export const CERTIFICATIONS_NAME_MAX = 40

export const CERTIFICATIONS_ORGANIZATION_MIN = 1
export const CERTIFICATIONS_ORGANIZATION_MAX = 40

export const CERTIFICATIONS_ORIGINAL_ID_MIN = 1
export const CERTIFICATIONS_ORIGINAL_ID_MAX = 256

export const CERTIFICATIONS_ORIGINAL_URL_MIN = 1
export const CERTIFICATIONS_ORIGINAL_URL_MAX = 1024

export default {
  CERTIFICATIONS_NAME_MIN: CERTIFICATIONS_NAME_MIN,
  CERTIFICATIONS_NAME_MAX: CERTIFICATIONS_NAME_MAX,
  CERTIFICATIONS_ORGANIZATION_MIN: CERTIFICATIONS_ORGANIZATION_MIN,
  CERTIFICATIONS_ORGANIZATION_MAX: CERTIFICATIONS_ORGANIZATION_MAX,
  CERTIFICATIONS_ORIGINAL_ID_MIN: CERTIFICATIONS_ORIGINAL_ID_MIN,
  CERTIFICATIONS_ORIGINAL_ID_MAX: CERTIFICATIONS_ORIGINAL_ID_MAX,
  CERTIFICATIONS_ORIGINAL_URL_MIN: CERTIFICATIONS_ORIGINAL_URL_MIN,
  CERTIFICATIONS_ORIGINAL_URL_MAX: CERTIFICATIONS_ORIGINAL_URL_MAX,
}

