'use strict'

export const EDUCATION_SCHOOL_MIN = 1
export const EDUCATION_SCHOOL_MAX = 256

export const EDUCATION_DEGREE_MIN = 1
export const EDUCATION_DEGREE_MAX = 128

export const EDUCATION_FIELD_MIN = 1
export const EDUCATION_FIELD_MAX = 128

export const EDUCATION_GRADE_MIN = 1
export const EDUCATION_GRADE_MAX = 40

export const EDUCATION_DESCRIPTION_MIN = 1
export const EDUCATION_DESCRIPTION_MAX = 1024

export default {
  EDUCATION_SCHOOL_MIN: EDUCATION_SCHOOL_MIN,
  EDUCATION_SCHOOL_MAX: EDUCATION_SCHOOL_MAX,
  EDUCATION_DEGREE_MIN: EDUCATION_DEGREE_MIN,
  EDUCATION_DEGREE_MAX: EDUCATION_DEGREE_MAX,
  EDUCATION_FIELD_MIN: EDUCATION_FIELD_MIN,
  EDUCATION_FIELD_MAX: EDUCATION_FIELD_MAX,
  EDUCATION_GRADE_MIN: EDUCATION_GRADE_MIN,
  EDUCATION_GRADE_MAX: EDUCATION_GRADE_MAX,
  EDUCATION_DESCRIPTION_MIN: EDUCATION_DESCRIPTION_MIN,
  EDUCATION_DESCRIPTION_MAX: EDUCATION_DESCRIPTION_MAX
}
