'use strict'

export const PROFESSIONAL_TITLE_MIN = 1
export const PROFESSIONAL_TITLE_MAX = 40

export const PROFESSIONAL_DESCRIPTION_MIN = 1
export const PROFESSIONAL_DESCRIPTION_MAX = 1024

export const PROFESSIONAL_COMPANY_MIN = 1
export const PROFESSIONAL_COMPANY_MAX = 40

export const PROFESSIONAL_LOCATION_MIN = 1
export const PROFESSIONAL_LOCATION_MAX = 40

export default {
  PROFESSIONAL_TITLE_MIN: PROFESSIONAL_TITLE_MIN,
  PROFESSIONAL_TITLE_MAX: PROFESSIONAL_TITLE_MAX,
  PROFESSIONAL_DESCRIPTION_MIN: PROFESSIONAL_DESCRIPTION_MIN,
  PROFESSIONAL_DESCRIPTION_MAX: PROFESSIONAL_DESCRIPTION_MAX,
  PROFESSIONAL_COMPANY_MIN: PROFESSIONAL_COMPANY_MIN,
  PROFESSIONAL_COMPANY_MAX: PROFESSIONAL_COMPANY_MAX,
  PROFESSIONAL_LOCATION_MIN: PROFESSIONAL_LOCATION_MIN,
  PROFESSIONAL_LOCATION_MAX: PROFESSIONAL_LOCATION_MAX
}
