'use strict'

export const PUBLICATIONS_TITLE_MIN = 1
export const PUBLICATIONS_TITLE_MAX = 128

export const PUBLICATIONS_PUBLISHER_MIN = 1
export const PUBLICATIONS_PUBLISHER_MAX = 128

export const PUBLICATIONS_AUTHORS_MIN = 1
export const PUBLICATIONS_AUTHORS_MAX = 1024

export const PUBLICATIONS_URL_MIN = 1
export const PUBLICATIONS_URL_MAX = 1024

export const PUBLICATIONS_DESCRIPTION_MIN = 1
export const PUBLICATIONS_DESCRIPTION_MAX = 10240

export default {
  PUBLICATIONS_TITLE_MIN: PUBLICATIONS_TITLE_MIN,
  PUBLICATIONS_TITLE_MAX: PUBLICATIONS_TITLE_MAX,
  PUBLICATIONS_PUBLISHER_MIN: PUBLICATIONS_PUBLISHER_MIN,
  PUBLICATIONS_PUBLISHER_MAX: PUBLICATIONS_PUBLISHER_MAX,
  PUBLICATIONS_AUTHORS_MIN: PUBLICATIONS_AUTHORS_MIN,
  PUBLICATIONS_AUTHORS_MAX: PUBLICATIONS_AUTHORS_MAX,
  PUBLICATIONS_URL_MIN: PUBLICATIONS_URL_MIN,
  PUBLICATIONS_URL_MAX: PUBLICATIONS_URL_MAX,
  PUBLICATIONS_DESCRIPTION_MIN: PUBLICATIONS_DESCRIPTION_MIN,
  PUBLICATIONS_DESCRIPTION_MAX: PUBLICATIONS_DESCRIPTION_MAX,
}

