'use strict'

export const SKILLS_NAME_MIN = 1
export const SKILLS_NAME_MAX = 40

export const SKILLS_DESCRIPTION_MIN = 1
export const SKILLS_DESCRIPTION_MAX = 1024

export default {
  SKILLS_NAME_MIN: SKILLS_NAME_MIN,
  SKILLS_NAME_MAX: SKILLS_NAME_MAX,
  SKILLS_DESCRIPTION_MIN: SKILLS_DESCRIPTION_MIN,
  SKILLS_DESCRIPTION_MAX: SKILLS_DESCRIPTION_MAX,
}
