'use strict'

export const VOLUNTEER_ROLE_MIN = 1
export const VOLUNTEER_ROLE_MAX = 40

export const VOLUNTEER_DESCRIPTION_MIN = 1
export const VOLUNTEER_DESCRIPTION_MAX = 1024

export const VOLUNTEER_ORGANIZATION_MIN = 1
export const VOLUNTEER_ORGANIZATION_MAX = 40

export const VOLUNTEER_LOCATION_MIN = 1
export const VOLUNTEER_LOCATION_MAX = 40

export default {
  VOLUNTEER_ROLE_MIN: VOLUNTEER_ROLE_MIN,
  VOLUNTEER_ROLE_MAX: VOLUNTEER_ROLE_MAX,
  VOLUNTEER_DESCRIPTION_MIN: VOLUNTEER_DESCRIPTION_MIN,
  VOLUNTEER_DESCRIPTION_MAX: VOLUNTEER_DESCRIPTION_MAX,
  VOLUNTEER_ORGANIZATION_MIN: VOLUNTEER_ORGANIZATION_MIN,
  VOLUNTEER_ORGANIZATION_MAX: VOLUNTEER_ORGANIZATION_MAX,
  VOLUNTEER_LOCATION_MIN: VOLUNTEER_LOCATION_MIN,
  VOLUNTEER_LOCATION_MAX: VOLUNTEER_LOCATION_MAX
}
